# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ihm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_ihm(object):
    def setupUi(self, main_ihm):
        main_ihm.setObjectName("main_ihm")
        main_ihm.resize(1013, 855)
        self.centralwidget = QtWidgets.QWidget(main_ihm)
        self.centralwidget.setObjectName("centralwidget")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(20, 10, 971, 661))
        self.container.setObjectName("container")
        self.bouton_simu = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_simu.setGeometry(QtCore.QRect(700, 700, 71, 31))
        self.bouton_simu.setObjectName("bouton_simu")
        self.bouton_pause = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_pause.setGeometry(QtCore.QRect(780, 700, 71, 31))
        self.bouton_pause.setObjectName("bouton_pause")
        self.bouton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_quitter.setGeometry(QtCore.QRect(860, 700, 71, 31))
        self.bouton_quitter.setObjectName("bouton_quitter")
        self.slider_vitesse = QtWidgets.QSlider(self.centralwidget)
        self.slider_vitesse.setGeometry(QtCore.QRect(30, 750, 160, 16))
        self.slider_vitesse.setMinimum(1)
        self.slider_vitesse.setMaximum(500)
        self.slider_vitesse.setProperty("value", 100)
        self.slider_vitesse.setOrientation(QtCore.Qt.Horizontal)
        self.slider_vitesse.setObjectName("slider_vitesse")
        self.label_slider_vitesse = QtWidgets.QLabel(self.centralwidget)
        self.label_slider_vitesse.setGeometry(QtCore.QRect(30, 680, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_slider_vitesse.setFont(font)
        self.label_slider_vitesse.setObjectName("label_slider_vitesse")
        self.bouton_gen = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_gen.setGeometry(QtCore.QRect(620, 700, 71, 31))
        self.bouton_gen.setObjectName("bouton_gen")
        self.LCD_vitesse = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_vitesse.setGeometry(QtCore.QRect(120, 690, 64, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LCD_vitesse.setFont(font)
        self.LCD_vitesse.setProperty("intValue", 100)
        self.LCD_vitesse.setObjectName("LCD_vitesse")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 680, 251, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinbox_nb_vehicle = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_nb_vehicle.setMaximumSize(QtCore.QSize(71, 16777215))
        self.spinbox_nb_vehicle.setMinimum(1)
        self.spinbox_nb_vehicle.setMaximum(100000)
        self.spinbox_nb_vehicle.setProperty("value", 40)
        self.spinbox_nb_vehicle.setObjectName("spinbox_nb_vehicle")
        self.gridLayout.addWidget(self.spinbox_nb_vehicle, 0, 1, 1, 1)
        self.label_longueur_route = QtWidgets.QLabel(self.layoutWidget)
        self.label_longueur_route.setObjectName("label_longueur_route")
        self.gridLayout.addWidget(self.label_longueur_route, 1, 0, 1, 1)
        self.label_nb_vehicle = QtWidgets.QLabel(self.layoutWidget)
        self.label_nb_vehicle.setObjectName("label_nb_vehicle")
        self.gridLayout.addWidget(self.label_nb_vehicle, 0, 0, 1, 1)
        self.spinbox_longueur_route = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_longueur_route.setMaximumSize(QtCore.QSize(71, 16777215))
        self.spinbox_longueur_route.setMinimum(100)
        self.spinbox_longueur_route.setMaximum(1000000)
        self.spinbox_longueur_route.setProperty("value", 500)
        self.spinbox_longueur_route.setObjectName("spinbox_longueur_route")
        self.gridLayout.addWidget(self.spinbox_longueur_route, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 690, 47, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.LCD_vitesse_moy = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_vitesse_moy.setGeometry(QtCore.QRect(750, 750, 64, 41))
        self.LCD_vitesse_moy.setProperty("intValue", 100)
        self.LCD_vitesse_moy.setObjectName("LCD_vitesse_moy")
        self.label_vitesse_moy = QtWidgets.QLabel(self.centralwidget)
        self.label_vitesse_moy.setGeometry(QtCore.QRect(670, 750, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_vitesse_moy.setFont(font)
        self.label_vitesse_moy.setObjectName("label_vitesse_moy")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 750, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.disp_img = QtWidgets.QSlider(self.centralwidget)
        self.disp_img.setGeometry(QtCore.QRect(380, 780, 41, 22))
        self.disp_img.setMaximum(1)
        self.disp_img.setPageStep(1)
        self.disp_img.setProperty("value", 1)
        self.disp_img.setOrientation(QtCore.Qt.Horizontal)
        self.disp_img.setObjectName("disp_img")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 780, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 780, 61, 21))
        self.label_4.setObjectName("label_4")
        main_ihm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_ihm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menubar.setObjectName("menubar")
        main_ihm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_ihm)
        self.statusbar.setObjectName("statusbar")
        main_ihm.setStatusBar(self.statusbar)

        self.retranslateUi(main_ihm)
        self.bouton_quitter.clicked.connect(main_ihm.close)
        self.slider_vitesse.valueChanged['int'].connect(self.LCD_vitesse.display)
        QtCore.QMetaObject.connectSlotsByName(main_ihm)

    def retranslateUi(self, main_ihm):
        _translate = QtCore.QCoreApplication.translate
        main_ihm.setWindowTitle(_translate("main_ihm", "MainWindow"))
        self.bouton_simu.setText(_translate("main_ihm", "Simuler"))
        self.bouton_pause.setText(_translate("main_ihm", "Pause"))
        self.bouton_quitter.setText(_translate("main_ihm", "Quitter"))
        self.label_slider_vitesse.setText(_translate("main_ihm", "Vitesse de \n"
"simulation"))
        self.bouton_gen.setText(_translate("main_ihm", "Générer "))
        self.label_longueur_route.setText(_translate("main_ihm", "Longueur route "))
        self.label_nb_vehicle.setText(_translate("main_ihm", "Nb véhicules "))
        self.label.setText(_translate("main_ihm", "%"))
        self.label_vitesse_moy.setText(_translate("main_ihm", "Vitesse \n"
"moyenne"))
        self.label_2.setText(_translate("main_ihm", "km/h"))
        self.label_3.setText(_translate("main_ihm", "Rectangles"))
        self.label_4.setText(_translate("main_ihm", "Images"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_ihm = QtWidgets.QMainWindow()
    ui = Ui_main_ihm()
    ui.setupUi(main_ihm)
    main_ihm.show()
    sys.exit(app.exec_())
